### ISSUE TITLE
Fix search bar

### ISSUE THREAD

**Issue by luis-madrigal** [luis-madrigal/LUNGSOD#4]
looks weird man
![capture](https://cloud.githubusercontent.com/assets/15045277/24151830/cb092918-0e84-11e7-8da3-1f7bf621f541.PNG)

**Comment by MaynardSi** [comment]
feels bad man

**Comment by MaynardSi** [comment]
![image](https://cloud.githubusercontent.com/assets/17776810/24232187/27513eaa-0fc4-11e7-84e7-739ffe201542.png)

Fixed among all screens in screentest
